pipeline {
  agent any
  environment {
    DOCKER_BUILDKIT = 1
  }
  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/YOUR_REPO/fullstack-devops-app.git'
      }
    }
    stage('Build Docker Images') {
      steps {
        sh 'docker-compose build'
      }
    }
    stage('Run Containers') {
      steps {
        sh 'docker-compose up -d'
      }
    }
    stage('Code Quality') {
      steps {
        sh 'docker run --rm -v $(pwd):/app sonarsource/sonar-scanner-cli'
      }
    }
  }
}
