pipeline {
  agent any
  environment {
    DOCKER_BUILDKIT = 1
  }
  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Sanjith027/Fullstack-Devops-App.git'
      }
    }
    stage('Build Docker Images') {
      steps {
        sh 'docker-compose build'
      }
    }
    stage('Run Containers') {
      steps {
        sh 'docker-compose up -d'
      }
    }
  }
}
